version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    volumes:
      - ./volumes/redis:/data
  web:
    build: ./src
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  celery:
    build: ./src
    command: celery -A pokecrawler worker -B -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./src:/code
    depends_on:
      - web
      - db