# Generated by Django 3.2.14 on 2022-07-30 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('identifier', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('desc', models.TextField(null=True)),
                ('freshness', models.DateTimeField(default=django.utils.timezone.now)),
                ('species', models.CharField(max_length=256)),
                ('base_experience', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_default', models.CharField(max_length=512, null=True)),
                ('front_shiny', models.CharField(max_length=512, null=True)),
                ('front_female', models.CharField(max_length=512, null=True)),
                ('front_shiny_female', models.CharField(max_length=512, null=True)),
                ('back_default', models.CharField(max_length=512, null=True)),
                ('back_shiny', models.CharField(max_length=512, null=True)),
                ('back_female', models.CharField(max_length=512, null=True)),
                ('back_shiny_female', models.CharField(max_length=512, null=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokeapp.pokemon')),
            ],
        ),
    ]
